export enum ConductorType {
  HTTP = "HTTP",
  HUMAN = "HUMAN",
  INLINE = "INLINE",
  SWITCH = "SWITCH",
  WAIT = "WAIT",
  BUSINESS_RULE = "SIMPLE_RULE",
  SIMPLE_EXCEPTION = "SIMPLE_EXCEPTION",
  SUB_WORKFLOW = "SUB_WORKFLOW",
  SIMPLE = "SIMPLE",
  SET_VARIABLE = "SET_VARIABLE",
}
