export enum FormTypes {
  Trigger = "trigger",
  Processor = "processor",
  Execution = "execution",
  UseAManage = "useManage",
  Disposition = "disposition",
  ExecuteRule = "executeRule",
  CreateException = "createException",
  ContentManagement = "contentManagement",
  Apps = "apps",
  Rot = "rot",
  Flow = "flow",
  AiAgents = "aiAgents",
  Default = "default",
  Inference = "inference",
  HTTP = "http",
  Switch = "switch",
}
