export enum NodeTypes {
  Trigger = "trigger",
  Input = "input",
  Process = "process",
  Output = "output",
  Custom = "custom_node",
  Processor = "processor",
  CoreWorkflow = "coreWorkflow",
  AiAgents = "aiAgents",
  Flow = "flow",
  Rot = "rot",
  Integrations = "integrations",
  ContentManagement = "contentManagement",
  Inference = "inference",
  Switch = "switch",
  SwitchEnd = "switchEnd",
  Fork = "fork",
  Join = "join",
  SubWorkflow = "subWorkflow",
  ExecuteRule = "executeRule",
  StickyNote = "stickyNote",
  Context = "context",
  Merge = "merge",
  Split = "split",
  Apps = "apps",
  JoinEnd = "joinEnd",
  SplitEnd = "splitEnd",
}
